### ISSUE TITLE
Haveing trouble compiling the code to run your recipe_manager

### ISSUE THREAD

**Issue by Joedog37** [FyefoxxM/recipe_manager#1]
i do cargo run and get this 

warning: build failed, waiting for other jobs to finish...

C:\Users\lordg\recipe_manager>cargo run
   Compiling wgpu-hal v0.14.1
   Compiling serde_json v1.0.132
error[E0308]: mismatched types
    --> C:\Users\lordg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.14.1\src\dx11\device.rs:233:13
     |
231  |         let ret = self.CheckFeatureSupport(
     |                        ------------------- arguments to this method are incorrect
232  |             feature,
233  |             &mut value as *mut T as *mut c_void,
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `winapi::ctypes::c_void`, found `std::ffi::c_void`
     |
     = note: `std::ffi::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
note: `std::ffi::c_void` is defined in crate `core`
    --> /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\ffi\mod.rs:193:1
note: `winapi::ctypes::c_void` is defined in crate `winapi`
    --> C:\Users\lordg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\lib.rs:38:5
     |
38   |     pub enum c_void {}
     |     ^^^^^^^^^^^^^^^
note: method defined here
    --> C:\Users\lordg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\um\d3d11.rs:3266:8
     |
3266 |     fn CheckFeatureSupport(
     |        ^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `wgpu-hal` (lib) due to 1 previous error

**Comment by FyefoxxM** [comment]
Hey man!
I think this is a problem with the hal build with cargo. I'll see if I can also include the wgpu in the commit.

**Comment by FyefoxxM** [comment]
I included my version of wgpu_hal.crate that you can open in VSCode and update your own file. It should work now. If you're still having issues let me know.

**Comment by Joedog37** [comment]
where do i put the file after i download it

**Comment by FyefoxxM** [comment]
If you search the project folder that you built your project in for wgpu_hal you should see a .crate file. Open the location and place the downloaded file in there. Then redo cargo run. Let me know if you're still having issue :)

**Comment by Joedog37** [comment]
still get this
C:\Users\lordg\recipe_manager>cargo run
   Compiling proc-macro2 v1.0.89
   Compiling unicode-ident v1.0.13
   Compiling autocfg v1.4.0
   Compiling cfg-if v1.0.0
   Compiling bitflags v1.3.2
   Compiling windows_x86_64_msvc v0.52.6
   Compiling byteorder v1.5.0
   Compiling syn v1.0.109
   Compiling windows-targets v0.52.6
   Compiling once_cell v1.20.2
   Compiling num-traits v0.2.19
   Compiling winapi v0.3.9
   Compiling serde v1.0.213
   Compiling quote v1.0.37
   Compiling syn v2.0.82
   Compiling thiserror v1.0.65
   Compiling crossbeam-utils v0.8.20
   Compiling log v0.4.22
   Compiling siphasher v0.3.11
   Compiling rand_core v0.6.4
   Compiling rand v0.8.5
   Compiling phf_shared v0.11.2
   Compiling approx v0.5.1
   Compiling lock_api v0.4.12
   Compiling slab v0.4.9
   Compiling version_check v0.9.5
   Compiling zerocopy-derive v0.7.35
   Compiling thiserror-impl v1.0.65
   Compiling parking_lot_core v0.9.10
   Compiling toml v0.5.11
   Compiling ahash v0.8.11
   Compiling zerocopy v0.7.35
   Compiling phf_generator v0.11.2
   Compiling windows-sys v0.59.0
   Compiling futures-core v0.3.31
   Compiling smallvec v1.13.2
   Compiling futures-sink v0.3.31
   Compiling memchr v2.7.4
   Compiling scopeguard v1.2.0
   Compiling futures-channel v0.3.31
   Compiling phf_macros v0.11.2
   Compiling find-crate v0.6.3
   Compiling winapi-util v0.1.9
   Compiling futures-macro v0.3.31
   Compiling indexmap v1.9.3
   Compiling pin-utils v0.1.0
   Compiling pin-project-lite v0.2.14
   Compiling futures-task v0.3.31
   Compiling futures-io v0.3.31
   Compiling raw-window-handle v0.5.2
   Compiling palette v0.6.1
   Compiling phf v0.11.2
   Compiling termcolor v1.4.1
   Compiling palette_derive v0.6.1
   Compiling futures-util v0.3.31
   Compiling parking_lot v0.12.3
   Compiling crossbeam-epoch v0.9.18
   Compiling libloading v0.7.4
   Compiling getrandom v0.2.15
   Compiling allocator-api2 v0.2.18
   Compiling bit-vec v0.6.3
   Compiling unicode-width v0.1.14
   Compiling libc v0.2.161
   Compiling bitflags v2.6.0
   Compiling ash v0.37.3+1.3.251
   Compiling ttf-parser v0.25.0
   Compiling num_cpus v1.16.0
   Compiling hashbrown v0.12.3
   Compiling static_assertions v1.1.0
   Compiling rayon-core v1.12.1
   Compiling gpu-descriptor-types v0.1.2
   Compiling hashbrown v0.14.5
   Compiling codespan-reporting v0.11.1
   Compiling bit-set v0.5.3
   Compiling futures-executor v0.3.31
   Compiling owned_ttf_parser v0.25.0
   Compiling crossbeam-deque v0.8.5
   Compiling ppv-lite86 v0.2.20
   Compiling spirv v0.2.0+1.5.4
   Compiling gpu-alloc-types v0.2.0
   Compiling ab_glyph_rasterizer v0.1.8
   Compiling unicode-xid v0.2.6
   Compiling rustc-hash v1.1.0
   Compiling hexf-parse v0.2.1
   Compiling cfg_aliases v0.1.1
   Compiling naga v0.10.1
   Compiling wgpu-core v0.14.2
   Compiling iced_core v0.8.1
   Compiling ab_glyph v0.2.29
   Compiling gpu-alloc v0.5.4
   Compiling rand_chacha v0.3.1
   Compiling futures v0.3.31
   Compiling gpu-descriptor v0.2.4
   Compiling d3d12 v0.5.0
   Compiling bytemuck_derive v1.8.0
   Compiling fxhash v0.2.1
   Compiling wgpu-types v0.14.1
   Compiling renderdoc-sys v0.7.1
   Compiling range-alloc v0.1.3
   Compiling cty v0.2.2
   Compiling windows_x86_64_msvc v0.36.1
   Compiling either v1.13.0
   Compiling arrayvec v0.7.6
   Compiling profiling v1.0.16
   Compiling rayon v1.10.0
   Compiling raw-window-handle v0.4.3
   Compiling bytemuck v1.19.0
   Compiling iced_futures v0.6.0
   Compiling iced_style v0.7.0
   Compiling twox-hash v1.6.3
   Compiling crossbeam-channel v0.5.13
   Compiling unicode-segmentation v1.12.0
   Compiling linked-hash-map v0.5.6
   Compiling glam v0.21.3
   Compiling str-buf v1.0.6
   Compiling xi-unicode v0.3.0
   Compiling rustc-hash v2.0.0
   Compiling glyph_brush_draw_cache v0.1.6
   Compiling glyph_brush_layout v0.2.4
   Compiling error-code v2.3.1
   Compiling iced_native v0.9.1
   Compiling twox-hash v2.0.0
   Compiling encase_derive_impl v0.3.0
   Compiling ordered-float v4.4.0
   Compiling glyph_brush v0.7.11
   Compiling encase_derive v0.3.0
   Compiling iced_graphics v0.7.0
   Compiling windows-sys v0.36.1
   Compiling clipboard-win v4.5.0
   Compiling raw-window-handle v0.3.4
   Compiling wgpu-hal v0.14.1
   Compiling euclid v0.22.11
error[E0308]: mismatched types
    --> C:\Users\lordg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\wgpu-hal-0.14.1\src\dx11\device.rs:233:13
     |
231  |         let ret = self.CheckFeatureSupport(
     |                        ------------------- arguments to this method are incorrect
232  |             feature,
233  |             &mut value as *mut T as *mut c_void,
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `winapi::ctypes::c_void`, found `std::ffi::c_void`
     |
     = note: `std::ffi::c_void` and `winapi::ctypes::c_void` have similar names, but are actually distinct types
note: `std::ffi::c_void` is defined in crate `core`
    --> /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\ffi\mod.rs:193:1
note: `winapi::ctypes::c_void` is defined in crate `winapi`
    --> C:\Users\lordg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\lib.rs:38:5
     |
38   |     pub enum c_void {}
     |     ^^^^^^^^^^^^^^^
note: method defined here
    --> C:\Users\lordg\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\um\d3d11.rs:3266:8
     |
3266 |     fn CheckFeatureSupport(
     |        ^^^^^^^^^^^^^^^^^^^

   Compiling instant v0.1.13
   Compiling const_panic v0.2.10
   Compiling svg_fmt v0.4.3
For more information about this error, try `rustc --explain E0308`.
error: could not compile `wgpu-hal` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...

**Comment by FyefoxxM** [comment]
Hmmm, can you open your wgpu_hal.crate file? If you can, copy-paste the data from the downloaded file. That should force a remake.

**Comment by Joedog37** [comment]
This Is what i have in my .cargo
![Screenshot 2024-10-23 102823](https://github.com/user-attachments/assets/217b9cab-8a2a-4258-9930-dddbf6b1b89c)
and this is what I have in my recipe_manager folder
![Screenshot 2024-10-23 103245](https://github.com/user-attachments/assets/ce85aba9-c568-4d46-8601-4994799c7d39)

**Comment by FyefoxxM** [comment]
When you double-click the error in your IDE, does it open up the wgpu_hal.crate file? I feel like it should. If it does, then you should be able to edit it and replace the file with the one I uploaded to the project.
If not, you may have to navigate to the file in your project folder and manually open it in your IDE, then copy-paste the code in the uploaded wgpu_hal.crate file from this project.

**Comment by Joedog37** [comment]
It won't open your program at all and I got the new rust program on my computer

**Comment by FyefoxxM** [comment]
Does that work with the code? The wgpu_hal crate comes from Rust itself, so fixing that problem might be a bit difficult.
